name: Embedded CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build, Format & Static Analysis
    runs-on: ubuntu-latest

    container:
      image: gingerbread07/arm-gnu-toolchain-15.3.rel1:latest
      options: --user root

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Mark workspace as safe for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Check code formatting
        run: |
          make format
          git diff --quiet

      - name: Build firmware
        run: make

      - name: Run static analysis
        run: make cppcheck